# The COURSPACE Recommendation Engine

## The Data - manual vector encoding
 - Utilized NC State's Course Catalog to record 11 required courses for each of the ten chosen majors
 - These courses were then represented as vectors based on their subject (ex: Humanities, physics, engineering)

## The Input - from an intuitive user interface
- Students can input the courses they have taken throughout highschool **along with a rating of how much they enjoyed the course**
    - The rating acts as weight when trying to assess the similarity between any two highschool and college course vectors
- These courses are classified as vectors in the same way as the college major data

## The Algorithm - weighted cosine similarity evaluation
- For each major in our minimal dataset, the weighted cosine similarity between each input highschool course vector and each college course vector in any given major is computed. The cosine similarity measure is essentially a measure of the angle between any two vectors:

![](cos_sim_demo.png)

- The sum of the pairwise cosine similariy scores between each major and the inputted highschool courses are normalized by the maximum similarity score, and the three majors that produce the greatest cosine similarity score are recommended to the students


In [483]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity, euclidean_distances
import numpy as np

### Now, let's get started with some demo code for this engine

In [484]:
# The cosine similarity between two indentical vectors is 1
cosine_similarity([[1,1]], [[1,1]])

array([[1.]])

In [485]:
# The cosine between two orthogonal vectors is 0
cosine_similarity([[0,1]], [[1,0]])

array([[0.]])

In [486]:
# variables for constructing feature vectors
# notice how there is a set number of subject categories, which allows us to encode a course
# as a vector
COURSE_CATEGORIES = ["social science", "humanities","mathematics","physics", 
                     "chemistry", "environmental science", 
                     "biology", "engineering","computer science"]
vector_template = [0 for i in COURSE_CATEGORIES]

# we are using cosine_similarity 
# but euclidean distance is also an option
distance_method = 1 # 0 for euclidean distance, 1 for cosine similarity

In [487]:
# Load original data (taken from NC State)
df1 = pd.read_excel("majors.xlsx",usecols = lambda col_name: ("vector" not in col_name.lower()))
df1

Mechanical Engineering  \
0   CH 101 - Chemistry - A Molecular Science (3 un...   
1   CH 102 - General Chemistry Laboratory (1 units...   
2   E 101 - Introduction to Engineering & Problem ...   
3   E 115 - Introduction to Computing Environments...   
4          MA 141 - Calculus I (4 units: C or better)   
5   ENG 101 Acad Writing Research (4 units: C- or ...   
6                                 Economics (3 units)   
7   CSC 113 - Introduction to Computing - MATLAB (...   
8         MA 241 - Calculus II (4 units: C or better)   
9   MSE 200 - Mechanical Properties of Structural ...   
10          MAE 416 - Mechanical Engineering Design (   

                                            Chemistry  \
0                                   General Chemistry   
1                          Advanced Writing (3 units)   
2                                   Organic Chemistry   
3                              Quantitative Chemistry   
4        MA 241 - Calculus II (4 units: C- or better)   
5       MA 242 - Calculus III (4 units: C- or better)   
6   MA 341 - Applied Differential Equations I (3 u...   
7   BCH 451 - Principles of Biochemistry (4 units:...   
8   CH 401 - Systematic Inorganic Chemistry I (3 u...   
9   CH 415 - Analytical Chemistry II (3 units: C- ...   
10            CH 442 - Advanced Synthetic Techniques    

                                              English  \
0         American Literature (3 units: C- or better)   
1          British Literature (3 units: C- or better)   
2            World Literature (3 units: C- or better)   
3                        Film (3 units: C- or better)   
4                 Linguistics (3 units: C- or better)   
5                    Rhetoric (3 units: C- or better)   
6                                           History I   
7                                          Philosophy   
8                                 Literature Elective   
9   ENG 494 - Special Topics in Linguistics (3 uni...   
10  ENG 210 - Introduction to Language and Linguis...   

                                              Biology  \
0                           Communication and Writing   
1   LSC 101 - Critical and Creative Thinking in th...   
2   BIO 181 - Introductory Biology: Ecology, Evolu...   
3   BIO 183 - Introductory Biology: Cellular and M...   
4   CH 101 - Chemistry - A Molecular Science (3 un...   
5                                            Genetics   
6                   Organic Chemistry & Lab (4 units)   
7                 Calculus II (3 units: C- or better)   
8               PY 131 - Conceptual Physics (4 units)   
9   MB 351 - General Microbiology (3 units: C- or ...   
10               Biochemistry (3 units: C- or better)   

                                              Physics  \
0                                    Advanced Writing   
1   PY 252 - Instrumental and Data Analysis for Ph...   
2   PY 401 - Quantum Physics I (3 units: C- or bet...   
3   PY 402 - Quantum Physics II (3 units: C- or be...   
4        PY 411 - Mechanics I (3 units: C- or better)   
5       PY 412 - Mechanics II (3 units: C- or better)   
6   MA 405 - Introduction to Linear Algebra (3 uni...   
7                  Statistics (3 units: C- or better)   
8   PY 251 - Introduction to Scientific Computing ...   
9                  Social Sciences Elective (6 units)   
10                                 Physical Chemistry   

                                     Computer-Science  \
0     CH 102 - General Chemistry Laboratory (1 units)   
1   PY 205 - Physics for Engineers and Scientists ...   
2   MA 305 - Introductory Linear Algebra and Matri...   
3   ST 370 - Probability and Statistics for Engine...   
4   CSC 116 - Introduction to Computing - Java (3 ...   
5   CSC 216 - Software Development Fundamentals (3...   
6                                            Calculus   
7   CSC 226 - Discrete Mathematics for Computer Sc...   
8            CSC 230 - C and Software Tools (0 units)   
9   Computing / Numerical Methods (3

In [488]:
# The courses are converted into their subjects (done manually)
df = pd.read_excel("majors.xlsx",usecols = lambda col_name: ("vector" in col_name.lower()))
df

Mechanical-Engineering_vectorized    Chemistry_vectorized  \
0                          Chemistry               Chemistry   
1                          Chemistry              Humanities   
2                        Engineering               Chemistry   
3                   Computer Science  Mathematics, Chemistry   
4                        Mathematics             Mathematics   
5            Humanities, Engineering             Mathematics   
6                     Social Science             Mathematics   
7      Computer Science, Engineering      Biology, Chemistry   
8                        Mathematics               Chemistry   
9               Engineering, Physics               Chemistry   
10              Engineering, Physics               Chemistry   

            English_vectorized              Biology_vectorized  \
0                   Humanities                      Humanities   
1                   Humanities                         Biology   
2                   Humanities  Biology, Environmental Science   
3                   Humanities                       Chemistry   
4               Social Science                       Chemistry   
5               Social Science            Biology, Mathematics   
6                   Humanities                       Chemistry   
7                   Humanities                     Mathematics   
8                   Humanities                         Physics   
9   Humanities, Social Science  Biology, Environmental Science   
10                  Humanities              Biology, Chemistry   

      Physics_vectorized    Computer-Science_vectorized  \
0             Humanities                      Chemistry   
1   Physics, Mathematics           Physics, Engineering   
2   Physics, Mathematics                    Mathematics   
3   Physics, Mathematics       Mathematics, Engineering   
4   Physics, Mathematics               Computer Science   
5   Physics, Mathematics  Computer Science, Engineering   
6            Mathematics                    Mathematics   
7            Mathematics  Mathematics, Computer Science   
8       Computer Science               Computer Science   
9         Social Science  Computer Science, Mathematics   
10    Physics, Chemistry   Humanities, Computer Science   

                   Education_vectorized  \
0            Humanities, Social Science   
1            Humanities, Social Science   
2   Humanities, Social Science, Biology   
3               Social Science, Biology   
4               Social Science, Biology   
5                        Social Science   
6                            Humanities   
7                            Humanities   
8                           Mathematics   
9            Humanities, Social Science   
10     Social Science, Computer Science   

                        Mathematics_vectorized          History_vectorized  \
0                Mathematics, Computer Science                  Humanities   
1                                  Mathematics                  Humanities   
2                                  Mathematics                  Humanities   
3                                  Mathematics                  Humanities   
4                Mathematics, Computer Science                  Humanities   
5   Mathematics, Computer Science, Engineering  Humanities, Social Science   
6                                  Mathematics                  Humanities   
7                                  Mathematics  Humanities, Social Science   
8                                  Mathematics  Humanities, Social Science   
9                                    Chemistry                  Humanities   
10                                  Humanities                  Humanities   

                Enviromental-Engineering_Vectorized  
0                                           Biology  
1                Environmental Science, Engineering  
2                Environmental Science, Engineering  
3                                         Chemistry  
4       

### Here are the functions that drive this engine

In [489]:
def string_to_vec(str):
    '''converts a string with a course subject keyword into a one-hot encoded vector'''
    element_list = str.lower().split(",")
    vector = vector_template.copy()
    for element in element_list:
        element_index_in_vector = COURSE_CATEGORIES.index(element.strip().lower())
        vector[element_index_in_vector] = 1
    return vector

In [490]:
# TAKE A LOOK AT HOW THE STRING_TO_VEC FUNCTION WORKS
# demo for string_to_vec function
print("Vector for a Chemistry Course:",string_to_vec("Chemistry"))
print("Vector for a Computer Science Course:",string_to_vec("Computer Science"))
print("Vector for a Chemistry & Computer Science Course (eg: Computational Chemistry):",string_to_vec("Computer Science, Chemistry"))

Vector for a Chemistry Course: [0, 0, 0, 0, 1, 0, 0, 0, 0]
Vector for a Computer Science Course: [0, 0, 0, 0, 0, 0, 0, 0, 1]
Vector for a Chemistry & Computer Science Course (eg: Computational Chemistry): [0, 0, 0, 0, 1, 0, 0, 0, 1]


In [491]:
# VECTORIZED DATA, APPLY STRING_TO_VEC TO EACH CELL IN OUR DATAFRAME
# apply this to each cell in our data
vector_df = df.copy().applymap(string_to_vec)
vector_df.columns = (column.split("_")[0] for column in vector_df.columns)
vector_df

Mechanical-Engineering                    Chemistry  \
0   [0, 0, 0, 0, 1, 0, 0, 0, 0]  [0, 0, 0, 0, 1, 0, 0, 0, 0]   
1   [0, 0, 0, 0, 1, 0, 0, 0, 0]  [0, 1, 0, 0, 0, 0, 0, 0, 0]   
2   [0, 0, 0, 0, 0, 0, 0, 1, 0]  [0, 0, 0, 0, 1, 0, 0, 0, 0]   
3   [0, 0, 0, 0, 0, 0, 0, 0, 1]  [0, 0, 1, 0, 1, 0, 0, 0, 0]   
4   [0, 0, 1, 0, 0, 0, 0, 0, 0]  [0, 0, 1, 0, 0, 0, 0, 0, 0]   
5   [0, 1, 0, 0, 0, 0, 0, 1, 0]  [0, 0, 1, 0, 0, 0, 0, 0, 0]   
6   [1, 0, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 1, 0, 0, 0, 0, 0, 0]   
7   [0, 0, 0, 0, 0, 0, 0, 1, 1]  [0, 0, 0, 0, 1, 0, 1, 0, 0]   
8   [0, 0, 1, 0, 0, 0, 0, 0, 0]  [0, 0, 0, 0, 1, 0, 0, 0, 0]   
9   [0, 0, 0, 1, 0, 0, 0, 1, 0]  [0, 0, 0, 0, 1, 0, 0, 0, 0]   
10  [0, 0, 0, 1, 0, 0, 0, 1, 0]  [0, 0, 0, 0, 1, 0, 0, 0, 0]   

                        English                      Biology  \
0   [0, 1, 0, 0, 0, 0, 0, 0, 0]  [0, 1, 0, 0, 0, 0, 0, 0, 0]   
1   [0, 1, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 0, 0, 0, 0, 1, 0, 0]   
2   [0, 1, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 0, 0, 0, 1, 1, 0, 0]   
3   [0, 1, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 0, 0, 1, 0, 0, 0, 0]   
4   [1, 0, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 0, 0, 1, 0, 0, 0, 0]   
5   [1, 0, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 1, 0, 0, 0, 1, 0, 0]   
6   [0, 1, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 0, 0, 1, 0, 0, 0, 0]   
7   [0, 1, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 1, 0, 0, 0, 0, 0, 0]   
8   [0, 1, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 0, 1, 0, 0, 0, 0, 0]   
9   [1, 1, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 0, 0, 0, 1, 1, 0, 0]   
10  [0, 1, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 0, 0, 1, 0, 1, 0, 0]   

                        Physics             Computer-Science  \
0   [0, 1, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 0, 0, 1, 0, 0, 0, 0]   
1   [0, 0, 1, 1, 0, 0, 0, 0, 0]  [0, 0, 0, 1, 0, 0, 0, 1, 0]   
2   [0, 0, 1, 1, 0, 0, 0, 0, 0]  [0, 0, 1, 0, 0, 0, 0, 0, 0]   
3   [0, 0, 1, 1, 0, 0, 0, 0, 0]  [0, 0, 1, 0, 0, 0, 0, 1, 0]   
4   [0, 0, 1, 1, 0, 0, 0, 0, 0]  [0, 0, 0, 0, 0, 0, 0, 0, 1]   
5   [0, 0, 1, 1, 0, 0, 0, 0, 0]  [0, 0, 0, 0, 0, 0, 0, 1, 1]   
6   [0, 0, 1, 0, 0, 0, 0, 0, 0]  [0, 0, 1, 0, 0, 0, 0, 0, 0]   
7   [0, 0, 1, 0, 0, 0, 0, 0, 0]  [0, 0, 1, 0, 0, 0, 0, 0, 1]   
8   [0, 0, 0, 0, 0, 0, 0, 0, 1]  [0, 0, 0, 0, 0, 0, 0, 0, 1]   
9   [1, 0, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 1, 0, 0, 0, 0, 0, 1]   
10  [0, 0, 0, 1, 1, 0, 0, 0, 0]  [0, 1, 0, 0, 0, 0, 0, 0, 1]   

                      Education                  Mathematics  \
0   [1, 1, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 1, 0, 0, 0, 0, 0, 1]   
1   [1, 1, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 1, 0, 0, 0, 0, 0, 0]   
2   [1, 1, 0, 0, 0, 0, 1, 0, 0]  [0, 0, 1, 0, 0, 0, 0, 0, 0]   
3   [1, 0, 0, 0, 0, 0, 1, 0, 0]  [0, 0, 1, 0, 0, 0, 0, 0, 0]   
4   [1, 0, 0, 0, 0, 0, 1, 0, 0]  [0, 0, 1, 0, 0, 0, 0, 0, 1]   
5   [1, 0, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 1, 0, 0, 0, 0, 1, 1]   
6   [0, 1, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 1, 0, 0, 0, 0, 0, 0]   
7   [0, 1, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 1, 0, 0, 0, 0, 0, 0]   
8   [0, 0, 1, 0, 0, 0, 0, 0, 0]  [0, 0, 1, 0, 0, 0, 0, 0, 0]   
9   [1, 1, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 0, 0, 1, 0, 0, 0, 0]   
10  [1, 0, 0, 0, 0, 0, 0, 0, 1]  [0, 1, 0, 0, 0, 0, 0, 0, 0]   

                        History     Enviromental-Engineering  
0   [0, 1, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 0, 0, 0, 0, 1, 0, 0]  
1   [0, 1, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 0, 0, 0, 1, 0, 1, 0]  
2   [0, 1, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 0, 0, 0, 1, 0, 1, 0]  
3   [0, 1, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 0, 0, 1, 0, 0, 0, 0]  
4   [0, 1, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 0, 0, 1, 1, 0, 0, 0]  
5   [1, 1, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 1, 0, 1, 0, 0, 0, 0]  
6   [0, 1, 0, 0, 0, 0, 0, 0, 0]  [1, 0, 0, 0, 0, 0, 0, 0, 0]  
7   [1, 1, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 1, 0, 0, 0, 0, 0, 0]  
8   [1, 1, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 0, 1, 0, 0, 0, 0, 0]  
9   [0, 1, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 0, 0, 0, 0, 0, 1, 0]  
10  [0, 1, 0, 0, 0, 0, 0, 0, 0]  [0, 0, 1, 0, 0, 1, 0, 1, 0]

In [492]:
# first, we create some dummy input
input = vector_df["Physics"].tolist() # choose the physics collumn as our input
                                      # if our engine works, physics and related subjects should be recomended
input

[[0, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 1, 0, 0, 0, 0]]

In [493]:
def get_course_distance_to_each_input(college_course, method = 1):
    total_course_distance = 0
    
    
    if method==1:
        func = cosine_similarity
    elif method == 0:
        func = euclidean_distances
        
        
    for hs_course in input:
        total_course_distance+=func([college_course],[hs_course])
    return total_course_distance

In [494]:
def get_major_distance_from_input(major):
    college_course_vectors = vector_df[major].tolist()
    total_distance = 0
    for college_course_vector in college_course_vectors:
        total_distance+=get_course_distance_to_each_input(college_course_vector, method = distance_method)
    num_of_comparisons = len(input)*len(college_course_vectors)
    major_distance = total_distance/num_of_comparisons
    return major_distance

In [495]:
def get_best_course():
    major_distances = []
    majors = vector_df.columns
    for major in majors:
        major_distances.append(get_major_distance_from_input(major))
   
    if distance_method == 1:
        reverse_bool = True
    else:
        reverse_bool = False
    
    major_distances_norm = normalize_scores(major_distances)
    
    scores = sorted(zip(major_distances_norm, majors), reverse=reverse_bool)
    return scores

In [496]:
def normalize_scores(scores):
    '''normalize by max value in list'''
    norm = [(float(i)/max(scores))*100 for i in scores] # multiply by 100 to format into a percent
    return norm

In [497]:
# run the engine
get_best_course()

[(array([[100.]]), 'Physics'),
 (array([[91.93379326]]), 'Mathematics'),
 (array([[61.47878065]]), 'Computer-Science'),
 (array([[49.97177211]]), 'Chemistry'),
 (array([[41.99961255]]), 'Mechanical-Engineering'),
 (array([[37.58081002]]), 'Enviromental-Engineering'),
 (array([[33.20483193]]), 'Biology'),
 (array([[32.14540804]]), 'Education'),
 (array([[23.47936183]]), 'History'),
 (array([[21.89057549]]), 'English')]